name: merge

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: "Cache SVU binary"
        if: ${{ github.event.head_commit.message != 'Automated version bump commit' }}
        uses: actions/cache@v3
        with:
          path: /usr/bin/svu
          key: svu-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            svu-${{ runner.os }}-

      - name: "Install SVU"
        if: ${{ github.event.head_commit.message != 'Automated version bump commit' }}
        run: |
          if [ ! -f /usr/bin/svu ]; then
            echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | sudo tee /etc/apt/sources.list.d/caarlos0.list
            sudo apt update
            sudo apt install svu
          fi

      - name: Get current version and calculate next version
        id: getversion
        if: ${{ github.event.head_commit.message != 'Automated version bump commit' }}
        run: |
          echo "currentversion=$(svu current --tag.prefix='')" >> $GITHUB_ENV
          echo "nextversion=$(svu next --tag.prefix='')" >> $GITHUB_ENV

      - name: Print versions
        if: ${{ github.event.head_commit.message != 'Automated version bump commit' }}
        run: |
          echo "Current Version: ${{ env.currentversion }}"
          echo "Next Version: ${{ env.nextversion }}"

      - uses: thejeff77/action-push-tag@v1.0.0
        if: ${{ env.nextversion != env.currentversion }}
        with:
          tag: v${{ env.nextversion }}
