name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  issues: write

jobs:
  build:
    name: releasing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: nightly
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
